cd "C:\Users\blueplanet\PycharmProjects\pythonStockEvaluation"
C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "%date:~0,4%%date:~5,2%%date:~8,2%"
C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "%date:~0,4%%date:~5,2%%date:~8,2%"

rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180521"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180522"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180523"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180524"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180525"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180528"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180529"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180530"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180531"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180601"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180604"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180605"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180606"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180607"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180608"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180611"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180612"

rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180521"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180522"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180523"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180524"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180525"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180528"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180529"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180530"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180531"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180601"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180604"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180605"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180606"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180607"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180608"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180611"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180612"
