cd "C:\Users\blueplanet\PycharmProjects\pythonStockEvaluation"
C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "%date:~0,4%%date:~5,2%%date:~8,2%"
C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "%date:~0,4%%date:~5,2%%date:~8,2%"

rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180807"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180808"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180809"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180810"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180813"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180814"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180815"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180816"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockKD "20180817"


rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180807"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180808"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180809"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180810"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180813"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180814"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180815"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180816"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py computeStockMA "20180817"
