cd "C:\Users\blueplanet\PycharmProjects\pythonStockEvaluation"
C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "%date:~0,4%%date:~5,2%%date:~8,2%"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180613"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180612"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180611"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180608"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180607"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180606"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180605"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180604"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180601"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180531"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180530"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180529"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180528"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180525"