cd "C:\Users\blueplanet\PycharmProjects\pythonStockEvaluation"
C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "%date:~0,4%%date:~5,2%%date:~8,2%"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180702"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180629"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180628"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180627"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180626"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180625"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180622"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180621"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180620"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180619"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180615"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180614"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180613"
rem C:\\Users\\blueplanet\\Anaconda3\\python.exe stockClassInstance.py getInstitutionalInvestors "20180612"